# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.6
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Addons for managing rental operations in Odoo
repo_name: Vertical Rental
repo_slug: vertical-rental
travis_apt_packages: []
travis_apt_sources: []
